appName: java-telegram-bot
environment: dev
namespace: dev
replicas: 1
imageRegistry: ***REMOVED***or
imageName: telegram_bot_java
imageTag: ffe3963
restartPolicy: Always
image:
  pullSecret: docker-regcred
